name: ldmvfi
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.13
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pip:
    - opencv-python==4.6.0.66
    - pudb==2022.1.3
    - imageio==2.22.3
    - imageio-ffmpeg==0.4.7
    - pytorch-lightning==1.7.7
    - omegaconf==2.2.3
    - test-tube==0.7.5
    - streamlit==1.14.0
    - einops==0.5.0
    - torch-fidelity==0.3.0
    - transformers==4.23.1
    - timm==0.6.12
    - cupy
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .

# conda create -n ldmvfi python=3.9
# conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
# pip install opencv-python==4.6.0.66 pudb==2022.1.3 imageio==2.22.3 imageio-ffmpeg==0.4.7 pytorch-lightning==1.7.7 omegaconf==2.2.3  test-tube==0.7.5 streamlit==1.14.0  einops==0.5.0 torch-fidelity==0.3.0 transformers==4.23.1
# pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
# pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
# pip install -e .
# pip install timm